# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3c1a2b97d22dd74adc5a40dcb848cf443721038606df0b140882ff2625b34d14d4e1fd40f6df310818cd33de8451e493c9e99986935f5119c5254d53e5673e8

test:
  secret_key_base: 401e90b259282101dc645bc09e43bc2b04254b85bc6f395d47ad01a8d342cd79a0da125cdf5e6964c29067b9e44a562a1c0049370a16898c8098187f9d595564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
